### PR TITLE
Fix configuration setting properties

### PR DESCRIPTION
**Pull request by jdnichollsc**
Hi my friend, thanks for your excellent contributions! This project is really amazing! 👍 
Please check my changes to use nativeDriver from ScaleAndOpacity component by default and other fixes :)

### CODE REVIEW

**Comment by xotahal** [comment]
Hey mate 👋Thanks for the contribution .. I need to add eslint to this project .. will merge it soon ...

**Comment by jdnichollsc** [comment]
Awesome, thanks mate!

**Comment by jdnichollsc** [comment]
@xotahal ohh but I can see `eslint` already in your dependencies

**Comment by xotahal** [comment]
@jdnichollsc Hey man 👋 Just updated the eslint and fix all error that came with the update. Could you please take a look on this and solve the conflict?

Just two more things I already saw:
1. The variable name - `startOnDidMount`. I used `animateOnDidMount`. We should keep it same for all components.
2. `useNativeDriver` - Not sure here if we do it as true by default or keep the default of React Native (which is false). What do you think? 🤔

**Comment by jdnichollsc** [comment]
Ok, let me see
1. What name do you prefer?
2. Keep the default of React Native is ok for me, but let me know if you want to change that
Good night!

**Comment by xotahal** [comment]
1. I was thinking it would be enough to have `initValue` and `value` (as we have anyway). And if the `initValue` is different of `value` we will animate it within did mount method. If not we just wait for change the value.

2. Let's go with RN's default. So `false` it is.

**Comment by jdnichollsc** [comment]
@xotahal Hi mate, please check my changes!
I would prefer to have control using the animateOnDidMount, but let me know 👍 
Thanks, Nicholls

**Comment by xotahal** [comment]
Looks almost good 👍

1. There is still this - startOnDidMount. Could we rename it to the animateOnDidMount
2. About animateOnDidMount vs initialValue

```js
<TranslateX
    initialValue={0}
    value={10}
/>
```
or
```js
<TranslateX
    initialValue={0}
    value={10}
    animateOnDidMount
/>
```

Now I am not talking about one more line in second snipet. Talking about a case when you use different `initialValue` than `value` but forget for `animateOnDidMount`. Then the `initialValue` is useless there.

**Comment by jdnichollsc** [comment]
1. Done!
2. what do you propose? validate if initialValue is different from null and value property?

**Comment by xotahal** [comment]
Yeah, something like this:

```js
  constructor(props) {
    super(props);

    const { value, initValue } = props;

    this.state = {
      scaleValue: new Animated.Value(initValue || value),
    };
  }
  componentDidMount() {
    const { initiValue, value } = this.props;

    if (initValue && initiValue !== value) {
      InteractionManager.runAfterInteractions().then(() => {
        this.move(this.props);
      });
    }
  }
```

What do you think? 🤔

**Comment by jdnichollsc** [comment]
mmm I don't know... but if you want I can change the code to do that.
After merge this pull request I want to publish an example from Youtube 😅

**Comment by xotahal** [comment]
Ok, let's leave it like this for now. We'll see ...

**Comment by xotahal** [comment]
@jdnichollsc Send me the youtube link, please 🙏 Will share it on my twitter - http://bit.ly/t-xotahal

**Comment by jdnichollsc** [comment]
Let me finish the video to share with you my friend! 🤘

**Pull request merged**
